/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "lis-pr.pb-c.h"
void   lte__relate__relate__data__init
                     (LTERELATE__RELATEDATA         *message)
{
  static LTERELATE__RELATEDATA init_value = LTE__RELATE__RELATE__DATA__INIT;
  *message = init_value;
}
size_t lte__relate__relate__data__get_packed_size
                     (const LTERELATE__RELATEDATA *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &lte__relate__relate__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lte__relate__relate__data__pack
                     (const LTERELATE__RELATEDATA *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &lte__relate__relate__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lte__relate__relate__data__pack_to_buffer
                     (const LTERELATE__RELATEDATA *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &lte__relate__relate__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LTERELATE__RELATEDATA *
       lte__relate__relate__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LTERELATE__RELATEDATA *)
     protobuf_c_message_unpack (&lte__relate__relate__data__descriptor,
                                allocator, len, data);
}
void   lte__relate__relate__data__free_unpacked
                     (LTERELATE__RELATEDATA *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &lte__relate__relate__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t lte__relate__relate__data__cmd__default_value = 0;
static const LTERELATE__INDEXTYPE lte__relate__relate__data__indextype__default_value = LTE__RELATE__INDEX__TYPE__BY_UNKNOWN;
static const ProtobufCFieldDescriptor lte__relate__relate__data__field_descriptors[9] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, cmd),
    NULL,
    &lte__relate__relate__data__cmd__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indextype",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, indextype),
    &lte__relate__index__type__descriptor,
    &lte__relate__relate__data__indextype__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imsi",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, imsi),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imei",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, imei),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msisdn",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, msisdn),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecgi",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, has_ecgi),
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, ecgi),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datasource",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, has_datasource),
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, datasource),
    &lte__relate__data__source__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, has_time),
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ret_value",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, has_ret_value),
    PROTOBUF_C_OFFSETOF(LTERELATE__RELATEDATA, ret_value),
    &lte__relate__return__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lte__relate__relate__data__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  6,   /* field[6] = datasource */
  5,   /* field[5] = ecgi */
  3,   /* field[3] = imei */
  2,   /* field[2] = imsi */
  1,   /* field[1] = indextype */
  4,   /* field[4] = msisdn */
  8,   /* field[8] = ret_value */
  7,   /* field[7] = time */
};
static const ProtobufCIntRange lte__relate__relate__data__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 11, 2 },
  { 15, 5 },
  { 22, 6 },
  { 24, 7 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lte__relate__relate__data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "LTE_RELATE.RELATE_DATA",
  "RELATEDATA",
  "LTERELATE__RELATEDATA",
  "LTE_RELATE",
  sizeof(LTERELATE__RELATEDATA),
  9,
  lte__relate__relate__data__field_descriptors,
  lte__relate__relate__data__field_indices_by_name,
  5,  lte__relate__relate__data__number_ranges,
  (ProtobufCMessageInit) lte__relate__relate__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue lte__relate__relate__type__enum_values_by_number[1] =
{
  { "UPDATE_USER_INFO", "LTE__RELATE__RELATE__TYPE__UPDATE_USER_INFO", 1 },
};
static const ProtobufCIntRange lte__relate__relate__type__value_ranges[] = {
{1, 0},{0, 1}
};
const ProtobufCEnumValueIndex lte__relate__relate__type__enum_values_by_name[1] =
{
  { "UPDATE_USER_INFO", 0 },
};
const ProtobufCEnumDescriptor lte__relate__relate__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LTE_RELATE.RELATE_TYPE",
  "RELATE_TYPE",
  "LTERELATE__RELATETYPE",
  "LTE_RELATE",
  1,
  lte__relate__relate__type__enum_values_by_number,
  1,
  lte__relate__relate__type__enum_values_by_name,
  1,
  lte__relate__relate__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue lte__relate__index__type__enum_values_by_number[2] =
{
  { "BY_UNKNOWN", "LTE__RELATE__INDEX__TYPE__BY_UNKNOWN", -1 },
  { "BY_IMSI", "LTE__RELATE__INDEX__TYPE__BY_IMSI", 3 },
};
static const ProtobufCIntRange lte__relate__index__type__value_ranges[] = {
{4294967295, 0},{3, 1},{0, 2}
};
const ProtobufCEnumValueIndex lte__relate__index__type__enum_values_by_name[2] =
{
  { "BY_IMSI", 1 },
  { "BY_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor lte__relate__index__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LTE_RELATE.INDEX_TYPE",
  "INDEX_TYPE",
  "LTERELATE__INDEXTYPE",
  "LTE_RELATE",
  2,
  lte__relate__index__type__enum_values_by_number,
  2,
  lte__relate__index__type__enum_values_by_name,
  2,
  lte__relate__index__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue lte__relate__data__source__enum_values_by_number[1] =
{
  { "FROM_CS", "LTE__RELATE__DATA__SOURCE__FROM_CS", 6 },
};
static const ProtobufCIntRange lte__relate__data__source__value_ranges[] = {
{6, 0},{0, 1}
};
const ProtobufCEnumValueIndex lte__relate__data__source__enum_values_by_name[1] =
{
  { "FROM_CS", 0 },
};
const ProtobufCEnumDescriptor lte__relate__data__source__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LTE_RELATE.DATA_SOURCE",
  "DATA_SOURCE",
  "LTERELATE__DATASOURCE",
  "LTE_RELATE",
  1,
  lte__relate__data__source__enum_values_by_number,
  1,
  lte__relate__data__source__enum_values_by_name,
  1,
  lte__relate__data__source__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue lte__relate__return__type__enum_values_by_number[3] =
{
  { "DATA_ERROR", "LTE__RELATE__RETURN__TYPE__DATA_ERROR", 0 },
  { "UPDATE_FAIL", "LTE__RELATE__RETURN__TYPE__UPDATE_FAIL", 1 },
  { "UPDATE_SUCCESS", "LTE__RELATE__RETURN__TYPE__UPDATE_SUCCESS", 2 },
};
static const ProtobufCIntRange lte__relate__return__type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex lte__relate__return__type__enum_values_by_name[3] =
{
  { "DATA_ERROR", 0 },
  { "UPDATE_FAIL", 1 },
  { "UPDATE_SUCCESS", 2 },
};
const ProtobufCEnumDescriptor lte__relate__return__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "LTE_RELATE.RETURN_TYPE",
  "RETURN_TYPE",
  "LTERELATE__RETURNTYPE",
  "LTE_RELATE",
  3,
  lte__relate__return__type__enum_values_by_number,
  3,
  lte__relate__return__type__enum_values_by_name,
  1,
  lte__relate__return__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
